# Generated by Django 5.2.6 on 2025-10-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_kk', models.CharField(max_length=200, null=True)),
                ('name_tg', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('topic', models.CharField(max_length=100)),
                ('topic_uz', models.CharField(max_length=100, null=True)),
                ('topic_en', models.CharField(max_length=100, null=True)),
                ('topic_kk', models.CharField(max_length=100, null=True)),
                ('topic_tg', models.CharField(max_length=100, null=True)),
                ('topic_tr', models.CharField(max_length=100, null=True)),
                ('performance', models.CharField(max_length=100)),
                ('performance_uz', models.CharField(max_length=100, null=True)),
                ('performance_en', models.CharField(max_length=100, null=True)),
                ('performance_kk', models.CharField(max_length=100, null=True)),
                ('performance_tg', models.CharField(max_length=100, null=True)),
                ('performance_tr', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advance')),
            ],
        ),
    ]
