# Generated by Django 5.2.6 on 2025-09-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_kk', models.CharField(max_length=255, null=True)),
                ('name_tg', models.CharField(max_length=255, null=True)),
                ('name_tr', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_uz', models.CharField(max_length=25, null=True)),
                ('name_en', models.CharField(max_length=25, null=True)),
                ('name_kk', models.CharField(max_length=25, null=True)),
                ('name_tg', models.CharField(max_length=25, null=True)),
                ('name_tr', models.CharField(max_length=25, null=True)),
                ('date', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('location_uz', models.CharField(max_length=200, null=True)),
                ('location_en', models.CharField(max_length=200, null=True)),
                ('location_kk', models.CharField(max_length=200, null=True)),
                ('location_tg', models.CharField(max_length=200, null=True)),
                ('location_tr', models.CharField(max_length=200, null=True)),
                ('title', models.CharField()),
                ('title_uz', models.CharField(null=True)),
                ('title_en', models.CharField(null=True)),
                ('title_kk', models.CharField(null=True)),
                ('title_tg', models.CharField(null=True)),
                ('title_tr', models.CharField(null=True)),
            ],
        ),
    ]
