# Generated by Django 5.2.6 on 2025-09-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_uz', models.CharField(max_length=250, null=True)),
                ('name_en', models.CharField(max_length=250, null=True)),
                ('name_kk', models.CharField(max_length=250, null=True)),
                ('name_tg', models.CharField(max_length=250, null=True)),
                ('name_tr', models.CharField(max_length=250, null=True)),
                ('more_name', models.CharField(max_length=50)),
                ('more_name_uz', models.CharField(max_length=50, null=True)),
                ('more_name_en', models.CharField(max_length=50, null=True)),
                ('more_name_kk', models.CharField(max_length=50, null=True)),
                ('more_name_tg', models.CharField(max_length=50, null=True)),
                ('more_name_tr', models.CharField(max_length=50, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='data')),
                ('title', models.CharField(max_length=50)),
                ('title_uz', models.CharField(max_length=50, null=True)),
                ('title_en', models.CharField(max_length=50, null=True)),
                ('title_kk', models.CharField(max_length=50, null=True)),
                ('title_tg', models.CharField(max_length=50, null=True)),
                ('title_tr', models.CharField(max_length=50, null=True)),
                ('title_desc', models.TextField()),
                ('title_desc_uz', models.TextField(null=True)),
                ('title_desc_en', models.TextField(null=True)),
                ('title_desc_kk', models.TextField(null=True)),
                ('title_desc_tg', models.TextField(null=True)),
                ('title_desc_tr', models.TextField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('file_name', models.CharField(max_length=50)),
                ('file_name_uz', models.CharField(max_length=50, null=True)),
                ('file_name_en', models.CharField(max_length=50, null=True)),
                ('file_name_kk', models.CharField(max_length=50, null=True)),
                ('file_name_tg', models.CharField(max_length=50, null=True)),
                ('file_name_tr', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relate_name', models.CharField(max_length=200)),
                ('relate_name_uz', models.CharField(max_length=200, null=True)),
                ('relate_name_en', models.CharField(max_length=200, null=True)),
                ('relate_name_kk', models.CharField(max_length=200, null=True)),
                ('relate_name_tg', models.CharField(max_length=200, null=True)),
                ('relate_name_tr', models.CharField(max_length=200, null=True)),
                ('relate_more', models.CharField(max_length=100)),
                ('relate_more_uz', models.CharField(max_length=100, null=True)),
                ('relate_more_en', models.CharField(max_length=100, null=True)),
                ('relate_more_kk', models.CharField(max_length=100, null=True)),
                ('relate_more_tg', models.CharField(max_length=100, null=True)),
                ('relate_more_tr', models.CharField(max_length=100, null=True)),
                ('relate_image', models.ImageField(blank=True, null=True, upload_to='relate')),
                ('relate_title', models.CharField(max_length=100)),
                ('relate_title_uz', models.CharField(max_length=100, null=True)),
                ('relate_title_en', models.CharField(max_length=100, null=True)),
                ('relate_title_kk', models.CharField(max_length=100, null=True)),
                ('relate_title_tg', models.CharField(max_length=100, null=True)),
                ('relate_title_tr', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
