# Generated by Django 5.2.6 on 2025-09-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outlook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_kk', models.CharField(max_length=255, null=True)),
                ('name_tg', models.CharField(max_length=255, null=True)),
                ('name_tr', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='outlook')),
                ('focus_name', models.CharField(max_length=100)),
                ('focus_name_uz', models.CharField(max_length=100, null=True)),
                ('focus_name_en', models.CharField(max_length=100, null=True)),
                ('focus_name_kk', models.CharField(max_length=100, null=True)),
                ('focus_name_tg', models.CharField(max_length=100, null=True)),
                ('focus_name_tr', models.CharField(max_length=100, null=True)),
                ('focus_desc', models.TextField()),
                ('focus_desc_uz', models.TextField(null=True)),
                ('focus_desc_en', models.TextField(null=True)),
                ('focus_desc_kk', models.TextField(null=True)),
                ('focus_desc_tg', models.TextField(null=True)),
                ('focus_desc_tr', models.TextField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('file_name', models.CharField(max_length=50)),
            ],
        ),
    ]
