# Generated by Django 5.2.6 on 2025-09-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_kk', models.CharField(max_length=200, null=True)),
                ('name_tg', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('see_more', models.CharField(max_length=50)),
                ('see_more_uz', models.CharField(max_length=50, null=True)),
                ('see_more_en', models.CharField(max_length=50, null=True)),
                ('see_more_kk', models.CharField(max_length=50, null=True)),
                ('see_more_tg', models.CharField(max_length=50, null=True)),
                ('see_more_tr', models.CharField(max_length=50, null=True)),
                ('category_name', models.CharField(max_length=50)),
                ('category_name_uz', models.CharField(max_length=50, null=True)),
                ('category_name_en', models.CharField(max_length=50, null=True)),
                ('category_name_kk', models.CharField(max_length=50, null=True)),
                ('category_name_tg', models.CharField(max_length=50, null=True)),
                ('category_name_tr', models.CharField(max_length=50, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='technical')),
                ('edu_name', models.CharField(max_length=200)),
                ('edu_name_uz', models.CharField(max_length=200, null=True)),
                ('edu_name_en', models.CharField(max_length=200, null=True)),
                ('edu_name_kk', models.CharField(max_length=200, null=True)),
                ('edu_name_tg', models.CharField(max_length=200, null=True)),
                ('edu_name_tr', models.CharField(max_length=200, null=True)),
                ('edu_desc', models.TextField()),
                ('edu_desc_uz', models.TextField(null=True)),
                ('edu_desc_en', models.TextField(null=True)),
                ('edu_desc_kk', models.TextField(null=True)),
                ('edu_desc_tg', models.TextField(null=True)),
                ('edu_desc_tr', models.TextField(null=True)),
            ],
        ),
    ]
