# Generated by Django 5.2.6 on 2025-09-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_name_uz', models.CharField(max_length=50, null=True)),
                ('category_name_en', models.CharField(max_length=50, null=True)),
                ('category_name_kk', models.CharField(max_length=50, null=True)),
                ('category_name_tg', models.CharField(max_length=50, null=True)),
                ('category_name_tr', models.CharField(max_length=50, null=True)),
                ('all_name', models.CharField(max_length=50)),
                ('all_name_uz', models.CharField(max_length=50, null=True)),
                ('all_name_en', models.CharField(max_length=50, null=True)),
                ('all_name_kk', models.CharField(max_length=50, null=True)),
                ('all_name_tg', models.CharField(max_length=50, null=True)),
                ('all_name_tr', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_kk', models.CharField(max_length=200, null=True)),
                ('title_tg', models.CharField(max_length=200, null=True)),
                ('title_tr', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('date', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
            ],
        ),
    ]
