# Generated by Django 5.2.6 on 2025-10-03 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='museum')),
            ],
        ),
        migrations.CreateModel(
            name='Mega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_kk', models.CharField(max_length=200, null=True)),
                ('name_tg', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_kk', models.CharField(max_length=200, null=True)),
                ('name_tg', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('file', models.FileField(help_text='Faqat PDF, DOCX yoki DOC fayllarni yuklang.', upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])])),
                ('button', models.CharField(max_length=150)),
                ('button_uz', models.CharField(max_length=150, null=True)),
                ('button_en', models.CharField(max_length=150, null=True)),
                ('button_kk', models.CharField(max_length=150, null=True)),
                ('button_tg', models.CharField(max_length=150, null=True)),
                ('button_tr', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_kk', models.CharField(max_length=100, null=True)),
                ('name_tg', models.CharField(max_length=100, null=True)),
                ('name_tr', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_kk', models.CharField(max_length=200, null=True)),
                ('name_tg', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('file', models.FileField(help_text='Faqat PDF, DOCX yoki DOC fayllarni yuklang.', upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])])),
                ('button', models.CharField(max_length=100)),
                ('button_uz', models.CharField(max_length=100, null=True)),
                ('button_en', models.CharField(max_length=100, null=True)),
                ('button_kk', models.CharField(max_length=100, null=True)),
                ('button_tg', models.CharField(max_length=100, null=True)),
                ('button_tr', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
