# Generated by Django 5.2.6 on 2025-09-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_uz', models.CharField(max_length=25, null=True)),
                ('name_en', models.CharField(max_length=25, null=True)),
                ('name_kk', models.CharField(max_length=25, null=True)),
                ('name_tg', models.CharField(max_length=25, null=True)),
                ('name_tr', models.CharField(max_length=25, null=True)),
                ('date', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('location_uz', models.CharField(max_length=200, null=True)),
                ('location_en', models.CharField(max_length=200, null=True)),
                ('location_kk', models.CharField(max_length=200, null=True)),
                ('location_tg', models.CharField(max_length=200, null=True)),
                ('location_tr', models.CharField(max_length=200, null=True)),
                ('title', models.CharField()),
                ('title_uz', models.CharField(null=True)),
                ('title_en', models.CharField(null=True)),
                ('title_kk', models.CharField(null=True)),
                ('title_tg', models.CharField(null=True)),
                ('title_tr', models.CharField(null=True)),
            ],
        ),
    ]
