# Generated by Django 5.2.6 on 2025-10-03 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_kk', models.CharField(max_length=100, null=True)),
                ('name_tg', models.CharField(max_length=100, null=True)),
                ('name_tr', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('area', models.CharField(max_length=200)),
                ('area_uz', models.CharField(max_length=200, null=True)),
                ('area_en', models.CharField(max_length=200, null=True)),
                ('area_kk', models.CharField(max_length=200, null=True)),
                ('area_tg', models.CharField(max_length=200, null=True)),
                ('area_tr', models.CharField(max_length=200, null=True)),
                ('part', models.CharField(max_length=200)),
                ('part_uz', models.CharField(max_length=200, null=True)),
                ('part_en', models.CharField(max_length=200, null=True)),
                ('part_kk', models.CharField(max_length=200, null=True)),
                ('part_tg', models.CharField(max_length=200, null=True)),
                ('part_tr', models.CharField(max_length=200, null=True)),
                ('contact', models.CharField(max_length=200)),
                ('contact_uz', models.CharField(max_length=200, null=True)),
                ('contact_en', models.CharField(max_length=200, null=True)),
                ('contact_kk', models.CharField(max_length=200, null=True)),
                ('contact_tg', models.CharField(max_length=200, null=True)),
                ('contact_tr', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Greeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_kk', models.CharField(max_length=200, null=True)),
                ('name_tg', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('file', models.FileField(help_text='Faqat PDF, DOCX yoki DOC fayllarni yuklang.', upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])])),
                ('button', models.CharField(max_length=50)),
                ('button_uz', models.CharField(max_length=50, null=True)),
                ('button_en', models.CharField(max_length=50, null=True)),
                ('button_kk', models.CharField(max_length=50, null=True)),
                ('button_tg', models.CharField(max_length=50, null=True)),
                ('button_tr', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_kk', models.CharField(max_length=100, null=True)),
                ('name_tg', models.CharField(max_length=100, null=True)),
                ('name_tr', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
