# Generated by Django 5.2.6 on 2025-10-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_kk', models.CharField(max_length=200, null=True)),
                ('name_tg', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=50)),
                ('address_uz', models.CharField(max_length=50, null=True)),
                ('address_en', models.CharField(max_length=50, null=True)),
                ('address_kk', models.CharField(max_length=50, null=True)),
                ('address_tg', models.CharField(max_length=50, null=True)),
                ('address_tr', models.CharField(max_length=50, null=True)),
                ('mail', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
    ]
