# Generated by Django 5.2.6 on 2025-09-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_kk', models.CharField(max_length=100, null=True)),
                ('name_tg', models.CharField(max_length=100, null=True)),
                ('name_tr', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project')),
            ],
        ),
    ]
