# Generated by Django 5.2.6 on 2025-09-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_kk', models.CharField(max_length=255, null=True)),
                ('name_tg', models.CharField(max_length=255, null=True)),
                ('name_tr', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_kk', models.CharField(max_length=255, null=True)),
                ('name_tg', models.CharField(max_length=255, null=True)),
                ('name_tr', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='itm/')),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('button_name', models.CharField(max_length=100)),
                ('button_name_uz', models.CharField(max_length=100, null=True)),
                ('button_name_en', models.CharField(max_length=100, null=True)),
                ('button_name_kk', models.CharField(max_length=100, null=True)),
                ('button_name_tg', models.CharField(max_length=100, null=True)),
                ('button_name_tr', models.CharField(max_length=100, null=True)),
                ('buttons_name', models.CharField(max_length=100)),
                ('buttons_name_uz', models.CharField(max_length=100, null=True)),
                ('buttons_name_en', models.CharField(max_length=100, null=True)),
                ('buttons_name_kk', models.CharField(max_length=100, null=True)),
                ('buttons_name_tg', models.CharField(max_length=100, null=True)),
                ('buttons_name_tr', models.CharField(max_length=100, null=True)),
                ('buttons_image', models.ImageField(blank=True, null=True, upload_to='home')),
                ('buttons_desc', models.CharField(max_length=100)),
                ('buttons_desc_uz', models.CharField(max_length=100, null=True)),
                ('buttons_desc_en', models.CharField(max_length=100, null=True)),
                ('buttons_desc_kk', models.CharField(max_length=100, null=True)),
                ('buttons_desc_tg', models.CharField(max_length=100, null=True)),
                ('buttons_desc_tr', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_name_uz', models.CharField(max_length=100, null=True)),
                ('category_name_en', models.CharField(max_length=100, null=True)),
                ('category_name_kk', models.CharField(max_length=100, null=True)),
                ('category_name_tg', models.CharField(max_length=100, null=True)),
                ('category_name_tr', models.CharField(max_length=100, null=True)),
                ('browse_link_name', models.CharField(max_length=100)),
                ('browse_link_name_uz', models.CharField(max_length=100, null=True)),
                ('browse_link_name_en', models.CharField(max_length=100, null=True)),
                ('browse_link_name_kk', models.CharField(max_length=100, null=True)),
                ('browse_link_name_tg', models.CharField(max_length=100, null=True)),
                ('browse_link_name_tr', models.CharField(max_length=100, null=True)),
                ('latest_image', models.ImageField(blank=True, null=True, upload_to='latest')),
                ('latest_title', models.CharField(max_length=200)),
                ('latest_title_uz', models.CharField(max_length=200, null=True)),
                ('latest_title_en', models.CharField(max_length=200, null=True)),
                ('latest_title_kk', models.CharField(max_length=200, null=True)),
                ('latest_title_tg', models.CharField(max_length=200, null=True)),
                ('latest_title_tr', models.CharField(max_length=200, null=True)),
                ('latest_date', models.DateTimeField(auto_now_add=True)),
                ('latest_desc', models.TextField()),
                ('latest_desc_uz', models.TextField(null=True)),
                ('latest_desc_en', models.TextField(null=True)),
                ('latest_desc_kk', models.TextField(null=True)),
                ('latest_desc_tg', models.TextField(null=True)),
                ('latest_desc_tr', models.TextField(null=True)),
            ],
        ),
    ]
