# Generated by Django 5.2.6 on 2025-10-03 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_kk', models.CharField(max_length=200, null=True)),
                ('name_tg', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('file', models.FileField(help_text='Faqat PDF, DOCX yoki DOC fayllarni yuklang.', upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])])),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_kk', models.CharField(max_length=200, null=True)),
                ('name_tg', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('topic', models.TextField()),
                ('topic_uz', models.TextField(null=True)),
                ('topic_en', models.TextField(null=True)),
                ('topic_kk', models.TextField(null=True)),
                ('topic_tg', models.TextField(null=True)),
                ('topic_tr', models.TextField(null=True)),
                ('link', models.CharField(max_length=200)),
                ('link_uz', models.CharField(max_length=200, null=True)),
                ('link_en', models.CharField(max_length=200, null=True)),
                ('link_kk', models.CharField(max_length=200, null=True)),
                ('link_tg', models.CharField(max_length=200, null=True)),
                ('link_tr', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
