# Generated by Django 5.2.6 on 2025-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_kk', models.CharField(max_length=200, null=True)),
                ('name_tg', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_kk', models.CharField(max_length=100, null=True)),
                ('title_tg', models.CharField(max_length=100, null=True)),
                ('title_tr', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('button', models.CharField(max_length=50)),
                ('button_uz', models.CharField(max_length=50, null=True)),
                ('button_en', models.CharField(max_length=50, null=True)),
                ('button_kk', models.CharField(max_length=50, null=True)),
                ('button_tg', models.CharField(max_length=50, null=True)),
                ('button_tr', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mem/')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_kk', models.CharField(max_length=100, null=True)),
                ('name_tg', models.CharField(max_length=100, null=True)),
                ('name_tr', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('column_name', models.CharField(max_length=50)),
                ('column_name_uz', models.CharField(max_length=50, null=True)),
                ('column_name_en', models.CharField(max_length=50, null=True)),
                ('column_name_kk', models.CharField(max_length=50, null=True)),
                ('column_name_tg', models.CharField(max_length=50, null=True)),
                ('column_name_tr', models.CharField(max_length=50, null=True)),
                ('column_desc', models.CharField(max_length=200)),
                ('column_desc_uz', models.CharField(max_length=200, null=True)),
                ('column_desc_en', models.CharField(max_length=200, null=True)),
                ('column_desc_kk', models.CharField(max_length=200, null=True)),
                ('column_desc_tg', models.CharField(max_length=200, null=True)),
                ('column_desc_tr', models.CharField(max_length=200, null=True)),
                ('column_button', models.CharField(max_length=50)),
                ('column_button_uz', models.CharField(max_length=50, null=True)),
                ('column_button_en', models.CharField(max_length=50, null=True)),
                ('column_button_kk', models.CharField(max_length=50, null=True)),
                ('column_button_tg', models.CharField(max_length=50, null=True)),
                ('column_button_tr', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
            ],
        ),
    ]
