# Generated by Django 5.2.6 on 2025-09-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eurosun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_kk', models.CharField(max_length=255, null=True)),
                ('name_tg', models.CharField(max_length=255, null=True)),
                ('name_tr', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField()),
                ('eco_desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='eco')),
            ],
        ),
    ]
