# Generated by Django 5.2.6 on 2025-10-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_kk', models.CharField(max_length=200, null=True)),
                ('name_tg', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='core')),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('core_name', models.CharField(max_length=255)),
                ('core_name_uz', models.CharField(max_length=255, null=True)),
                ('core_name_en', models.CharField(max_length=255, null=True)),
                ('core_name_kk', models.CharField(max_length=255, null=True)),
                ('core_name_tg', models.CharField(max_length=255, null=True)),
                ('core_name_tr', models.CharField(max_length=255, null=True)),
                ('core_image', models.ImageField(blank=True, null=True, upload_to='cores')),
                ('core_desc', models.TextField()),
                ('core_desc_uz', models.TextField(null=True)),
                ('core_desc_en', models.TextField(null=True)),
                ('core_desc_kk', models.TextField(null=True)),
                ('core_desc_tg', models.TextField(null=True)),
                ('core_desc_tr', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_kk', models.CharField(max_length=255, null=True)),
                ('name_tg', models.CharField(max_length=255, null=True)),
                ('name_tr', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_kk', models.CharField(max_length=200, null=True)),
                ('name_tg', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tess')),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('link', models.CharField(max_length=150)),
                ('img', models.ImageField(blank=True, null=True, upload_to='youtube')),
            ],
        ),
    ]
