# Generated by Django 5.2.6 on 2025-10-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_kk', models.TextField(null=True)),
                ('desc_tg', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_kk', models.CharField(max_length=200, null=True)),
                ('name_tg', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('awards', models.CharField(max_length=200)),
                ('awards_uz', models.CharField(max_length=200, null=True)),
                ('awards_en', models.CharField(max_length=200, null=True)),
                ('awards_kk', models.CharField(max_length=200, null=True)),
                ('awards_tg', models.CharField(max_length=200, null=True)),
                ('awards_tr', models.CharField(max_length=200, null=True)),
                ('achieve', models.CharField(max_length=200)),
                ('achieve_uz', models.CharField(max_length=200, null=True)),
                ('achieve_en', models.CharField(max_length=200, null=True)),
                ('achieve_kk', models.CharField(max_length=200, null=True)),
                ('achieve_tg', models.CharField(max_length=200, null=True)),
                ('achieve_tr', models.CharField(max_length=200, null=True)),
                ('lead', models.CharField(max_length=200)),
                ('lead_uz', models.CharField(max_length=200, null=True)),
                ('lead_en', models.CharField(max_length=200, null=True)),
                ('lead_kk', models.CharField(max_length=200, null=True)),
                ('lead_tg', models.CharField(max_length=200, null=True)),
                ('lead_tr', models.CharField(max_length=200, null=True)),
                ('fell', models.CharField(max_length=200)),
                ('fell_uz', models.CharField(max_length=200, null=True)),
                ('fell_en', models.CharField(max_length=200, null=True)),
                ('fell_kk', models.CharField(max_length=200, null=True)),
                ('fell_tg', models.CharField(max_length=200, null=True)),
                ('fell_tr', models.CharField(max_length=200, null=True)),
                ('chall', models.CharField(max_length=200)),
                ('chall_uz', models.CharField(max_length=200, null=True)),
                ('chall_en', models.CharField(max_length=200, null=True)),
                ('chall_kk', models.CharField(max_length=200, null=True)),
                ('chall_tg', models.CharField(max_length=200, null=True)),
                ('chall_tr', models.CharField(max_length=200, null=True)),
                ('jour', models.CharField(max_length=200)),
                ('jour_uz', models.CharField(max_length=200, null=True)),
                ('jour_en', models.CharField(max_length=200, null=True)),
                ('jour_kk', models.CharField(max_length=200, null=True)),
                ('jour_tg', models.CharField(max_length=200, null=True)),
                ('jour_tr', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='link/')),
            ],
        ),
    ]
